general_tab = "ul#profile-tabs li >> text=General"
communication_tab = "ul#profile-tabs li >> text=Communication"
social_tab = "ul#profile-tabs li >> text=Social bookmarks"

first_name_input = "#profile-firstname"
last_name_input = "#profile-lastname"
title_input = "#profile-title"
gender_select = "#profile-gender"
street_input = "#profile-street"
zip_input = "#profile-zip"
city_input = "#profile-city"
country_select = "#profile-country"
state_input = "#profile-state"
birthday_input = "#profile-birthday"
hide_year_checkbox = "#profile-birthday_hide_year"
about_textarea = "#profile-about"

phone_private_input = "#profile-phone_private"
phone_work_input = "#profile-phone_work"
mobile_input = "#profile-mobile"
fax_input = "#profile-fax"
xmpp_input = "#profile-im_xmpp"

website_input = "#profile-url"
facebook_input = "#profile-url_facebook"
linkedin_input = "#profile-url_linkedin"
instagram_input = "#profile-url_instagram"
xing_input = "#profile-url_xing"
youtube_input = "#profile-url_youtube"
vimeo_input = "#profile-url_vimeo"
tiktok_input = "#profile-url_tiktok"
twitter_input = "#profile-url_twitter"
mastodon_input = "#profile-url_mastodon"

save_button = "button[name='save']"

first_name_error = ".field-profile-firstname .help-block-error"
last_name_error = ".field-profile-lastname .help-block-error"

status_message_span = "#status-bar .status-bar-content span"
